web_interface/frenchmethod/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('manuals/', include('manuals.urls')),
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

web_interface/manuals/urls.py
from django.urls import path

from . import views


app_name = 'manuals'

urlpatterns = [
    path('',
         views.IndexView.as_view(),
         name='index'),
    
    path('<int:pk>/',
         views.ManualView.as_view(),
         name='manual_text'),
    
    path('<int:pk>/annotations/',
         views.ManualAnnotationsView.as_view(),
         name='manual_annotations'),
    
    path('json/annotations/<str:manual>',
         views.AnnotationsJson.as_view(),
         name='annotations_json_all'),
    
    path('json/annotations/<str:manual>/<str:section>/<str:paragraph>/<str:index>',
         views.AnnotationsJson.as_view(),
         name='annotations_json'),
]

web_interface/manuals/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Note(models.Model):
    author = models.CharField(max_length=200)
    text = models.CharField(max_length=200)

########################

class Statement(models.Model):
    
    class StatementType(models.TextChoices):
        ANY = 'Any', 'Any'
        STATEMENT = 'Statement', 'Statement'
        ADVICE = 'Advice', 'Advice'
        OPINION = 'Opinion', 'Opinion'
        DEFINITION = 'Definition', 'Definition'
        
    type = models.CharField(max_length=20,
                            choices=StatementType.choices,
                            default=StatementType.ANY)
    subject = models.CharField(max_length=100)
    text = models.CharField(max_length=1000)

########################

class Name(models.Model):
    value = models.CharField(max_length=100)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['value'], name='unique value')
        ]
        
class Ontology(MPTTModel):
    names = models.ManyToManyField(Name)
    description = models.CharField(max_length=1000)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children')

########################

class Annotation(models.Model):
    manual = models.CharField(max_length=20)
    section = models.CharField(max_length=20)
    paragraph = models.CharField(max_length=20)
    sentence = models.CharField(max_length=20)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    class Meta:
        ordering = ['section', 'paragraph', 'sentence']

########################

class SectionManager(models.Manager):
    def get_by_natural_key(self, index):
        return self.get(index=index)
    
class Section(models.Model):
    title = models.CharField(max_length=2000)
    manual = models.CharField(max_length=200, default='m')
    section = models.CharField(max_length=200, default='x')
    level = models.PositiveIntegerField()
    objects = SectionManager()
    
    def natural_key(self):
        return (self.manual, self.section)
    
    class Meta:
        #indexes = [ models.Index(fields=['index']) ]
        unique_together = [['manual', 'section']]

class ParagraphManager(models.Manager):
    def get_by_natural_key(self, section, index):
        return self.get(section=section, index=index)
    
class Paragraph(models.Model):
    manual = models.CharField(max_length=200, default='m')
    section = models.CharField(max_length=200, default='x')
    paragraph = models.CharField(max_length=200, default='y')
    objects = ParagraphManager()
    
    def natural_key(self):
        return (self.manual, self.section, self.paragraph)
    
    class Meta:
        #indexes = [ models.Index(fields=['index']) ]
        unique_together = [['manual', 'section', 'paragraph']]
        #ordering = ('tree_id', 'lft')
        #order_insertion_by = 'title'
        
class SentenceManager(models.Manager):
    def get_by_natural_key(self, section, paragraph, index):
        return self.get(section=section, paragraph=paragraph, index=index)
    
class Sentence(models.Model):
    text = models.CharField(max_length=2000)
    manual = models.CharField(max_length=200, default='m')
    section = models.CharField(max_length=200, default='x')
    paragraph = models.CharField(max_length=200, default='y')
    index = models.CharField(max_length=200, default='z')
    objects = ParagraphManager()
    
    def natural_key(self):
        return (self.manual, self.section, self.paragraph, self.index)
    
    class Meta:
        #indexes = [ models.Index(fields=['index']) ]
        unique_together = [['manual', 'section', 'paragraph', 'index']]

        
class TextNode(MPTTModel):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children')
    

        
class ManualManager(models.Manager):
    def get_by_natural_key(self, label):
        return self.get(label=label)
    
class Manual(models.Model):
    title = models.CharField(max_length=200, null=False)
    authors = models.CharField(max_length=100, null=True)
    year = models.IntegerField(null=True)
    label = models.CharField(max_length=100, default='?')
    text = models.ForeignKey(TextNode, on_delete=models.CASCADE)
    class Meta:
        #indexes = [ models.Index(fields=['index']) ]
        unique_together = ['label']

web_interface/manuals/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.http import JsonResponse
from django.core import serializers
import json

from .models import *

class IndexView(generic.ListView):
    def get_queryset(self):
        return Manual.objects.order_by('-title')

class ManualView(generic.DetailView):
    model = Manual
    template_name = 'manuals/manual_text.html'

class ManualAnnotationsView(generic.DetailView):
    model = Manual
    template_name = 'manuals/manual_annotations.html'

class AnnotationsJson(generic.ListView):
    http_method_names = ['get']
        
    def get_queryset(self):
        manual = self.kwargs['manual']
        if 'section' in self.kwargs:
            section = self.kwargs['section']
            paragraph = self.kwargs['paragraph']
            sentence = self.kwargs['index']
            return Annotation.objects.filter(manual=manual, section=section,
                                             paragraph=paragraph, sentence=sentence)
        else:
            return Annotation.objects.filter(manual=manual)

    def get_type(self, e):
        if e.content_type.model == 'statement':
            return e.content_object.type
        elif e.content_type.model == 'ontology':
            return 'Ontology'
        else:
            return 'Unknown'

    def get_content(self, e):
        if e.content_type.model == 'statement':
            return {
                'subject': e.content_object.subject,
                'text': e.content_object.text
            }
        elif e.content_type.model == 'ontology':
            o = e.content_object
            content = {
                'names': [name.value for name in o.names.all()],
                'description': o.description,
                'children': []
            }
            for child in o.get_children():
                c = {
                    'names': [name.value for name in child.names.all()],
                    'description': child.description
                }
                content['children'].append(c)
            return content
        else:
            return {}
        
    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        annotations = []
        for e in queryset:
            print(f"{e.content_type}")
            annotation = {
                'manual': e.manual,
                'section': e.section,
                'paragraph': e.paragraph,
                'sentence': e.sentence,
                'type': self.get_type(e),
                'content': self.get_content(e)
            }
            annotations.append(annotation)
        #data = serializers.serialize("json", queryset)
        return JsonResponse(json.dumps(annotations), status=200, safe=False)

web_interface/manuals/templates/manuals/annotation_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Manuals</title>
  </head>
  <body>
    {% if annotation_list %}
    {% for annotation in annotation_list %}
    <div>
      <div>
        {{ annotation.type }}
      </div>
      <div>
        {{ annotation.text }}
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No annotations.</p>
    {% endif %}
      </body>
</html>

web_interface/manuals/templates/manuals/manual_annotated.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Manuals - {{ manual.title }}</title>
    
    {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/bootstrap.min.css %}">
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/manual.css' %}">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container">
        <a href="#" class="navbar-brand">
            <img src="assets/images/romi_logo_icon.svg" height="54" alt="ROMI">
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="index.html" class="nav-item nav-link active">Manuals</a>
            <a href="about.html" class="nav-item nav-link">About</a>
          </div>
        </div>
        
      </div>
    </nav>

    
    <div class="container-fluid">
      <div class="row">

        <div class="col-md-6">
        
          <div class="manual-title-section">
            <h1 class="manual-title">{{ manual.title }}</h1>
            <p class="manual-info">
              <span class="manual-authors">{{ manual.authors }}</span>
              <span class="manual-year">({{ manual.year }})</span>
            </p>
          </div>

          {% load mptt_tags %}
          {% load class_tag %}
          
          {% full_tree_for_model manuals.TextNode as nodes %}
          {% recursetree nodes %}
          {% with node.content_object|get_class as type %}
          
          {% if type == 'Section' %}
          <div class="manual-section">
            <p class="manual-section-title">{{ node.content_object.title }}</p>
            {{ children }}
          </div>
          {% endif %}
          
          {% if type == 'Paragraph' %}
          <p class="manual-paragraph">
            {{ children }}
          </p>
          {% endif %}
          
          {% if type == 'Sentence' %}
          <span class="manual-sentence">
            {{ node.content_object.text }}
          </span>
          {% endif %}
          
          {% endwith %}
          {% endrecursetree %}

        </div>
        <div class="col-md-6">

        </div> <!-- col-?-6 -->
      </div> <!-- row -->
    </div> <!-- container -->
    
    <script src="{% static 'manuals/js/jquery.min.js' %}"></script>
    <script src="{% static 'manuals/js/bootstrap.min.js' %}"></script>
    
  </body>
</html>

web_interface/manuals/templates/manuals/manual_annotations.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Manuals - {{ manual.title }}</title>
    
    {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/manual.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="{% url 'manuals:index' %}" class="nav-item nav-link active">Manuals</a>
            <a href="about.html" class="nav-item nav-link">About</a>
          </div>
        </div>
        
      </div>
    </nav>
    
    <div class="container-fluid">
      <div class="manual">

        <div class="row">
          <div class="col-md-7">
            <div class="manual-title-section">
              <h1 class="manual-title">{{ manual.title }}</h1>
              <p class="manual-info">
                <span class="manual-authors">{{ manual.authors }}</span>
                <span class="manual-year">({{ manual.year }})</span>
              </p>
            </div>
          </div>
          <div class="col-md-5">
          </div>
        </div>
        
        <div class="row mb-4">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'manuals:manual_text' manual.pk %}">Text</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Annotations</a>
            </li>
          </ul>
        </div>

        <div class="row">
          <div class="col-md-7">
            <div class="manual-annotation-list" id="manual-annotation-list">
            </div>
          </div>
          <div class="col-md-5">
          </div>
        </div>
      </div>
    </div> <!-- container -->
    
    <script src="{% static 'manuals/js/jquery.min.js' %}"></script>
    <script src="{% static 'manuals/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'manuals/js/manual.js' %}"></script>

    <script>
      $(function() {
          initManual('{{ manual.label }}');
          loadAllAnnotation("{% url 'manuals:annotations_json_all' manual.label %}");
      });
    </script>
    
  </body>
</html>

web_interface/manuals/templates/manuals/manual_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Manuals</title>
    
    {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/manual.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="{% url 'manuals:index' %}" class="nav-item nav-link active">Manuals</a>
            <a href="about.html" class="nav-item nav-link">About</a>
          </div>
        </div>
        
      </div>
    </nav>
    
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-7">
          {% if manual_list %}
          <ul class="list-group manuals">
            {% for manual in manual_list %}
            <li class="list-group-item manuals-manual"><a class="manuals-title" href="{% url 'manuals:manual_text' manual.id %}">{{ manual.title }}</a></li>
            {% endfor %}
          </ul>
          {% else %}
          <p>No manuals.</p>
          {% endif %}
          <div class="col-md-5">
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'manuals/js/jquery.min.js' %}"></script>
    <script src="{% static 'manuals/js/bootstrap.min.js' %}"></script>
    
  </body>
</html>

web_interface/manuals/templates/manuals/manual_text.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Manuals - {{ manual.title }}</title>
    
    {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'manuals/css/manual.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="{% url 'manuals:index' %}" class="nav-item nav-link active">Manuals</a>
            <a href="about.html" class="nav-item nav-link">About</a>
          </div>
        </div>
        
      </div>
    </nav>
    
    <div class="container-fluid">
      <div class="manual">

        <div class="row">
          <div class="col-md-7">
            <div class="manual-title-section">
              <h1 class="manual-title">{{ manual.title }}</h1>
              <p class="manual-info">
                <span class="manual-authors">{{ manual.authors }}</span>
                <span class="manual-year">({{ manual.year }})</span>
              </p>
            </div>
          </div>
          <div class="col-md-5">
          </div>
        </div>

        <div class="row">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Text</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'manuals:manual_annotations' manual.pk %}">Annotations</a>
            </li>
          </ul>
        </div>
        
        {% load mptt_tags %}
        {% load get_class %}
        
        {% full_tree_for_model manuals.TextNode as nodes %}
        {% recursetree nodes %}
        {% with node.content_object|get_class as type %}
        
        {% if type == 'Section' %}
        <div class="row">
          <div class="col-md-7">
            <div class="manual-section">
              <p class="manual-section-title manual-title-level-{{ node.content_object.level }}">{{ node.content_object.title }}</p>
            </div>
          </div>
          <div class="col-md-5">
          </div>
        </div>
        {{ children }}
        {% endif %}
        
        {% if type == 'Paragraph' %}
        {% with node.content_object.section as section %}
        {% with node.content_object.paragraph as paragraph %}
        <div class="row manual-paragraph">
          <div class="col-md-7">
            {{ children }}
          </div>
          <div class="col-md-5">
          <div class="manual-paragraph-annotations" id="paragraph-{{ section }}-{{ paragraph }}">
          </div>
          </div>
        </div>
        {% endwith %}
        {% endwith %}
        {% endif %}
        
        {% if type == 'Sentence' %}
        {% with node.content_object.section as section %}
        {% with node.content_object.paragraph as paragraph %}
        {% with node.content_object.index as sentence %}
        <a class="manual-sentence-link" onclick="javascript:toggleAnnotations('{{ section }}', '{{ paragraph }}', '{{ sentence }}', '{% url 'manuals:annotations_json' node.content_object.manual section paragraph sentence %}')"> 
            <span class="manual-sentence" id="sentence-{{ section }}-{{ paragraph }}-{{ sentence }}">{{ node.content_object.text }}</span>
        </a>
        {% endwith %}
        {% endwith %}
        {% endwith %}
        {% endif %}
        
        {% endwith %}
        {% endrecursetree %}

      </div>
    </div> <!-- container -->
    
    <script src="{% static 'manuals/js/jquery.min.js' %}"></script>
    <script src="{% static 'manuals/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'manuals/js/manual.js' %}"></script>

    <script>
      $(function() { initManual('{{ manual.label }}'); });
    </script>
    
  </body>
</html>